
export const GENRE_LIST_RETRIEVED = "GENRE_LIST_RETRIEVED"
export const RESTAURANTS_RETRIEVED = "RESTAURANTS_RETRIEVED"
export const CHANGE_PAGE = "CHANGE_PAGE"
export const SELECT_GENRE = "SELECT_GENRE"
export const SEARCH_TERM = "SEARCH_TERM"